### PR TITLE
Create readme.md

### PR DESCRIPTION
**Pull request by sarahlukens**
Add open source datasets

### CODE REVIEW

**Review by sarahlukens — COMMENTED** [review]
how do I create a pull request for the most recent update to this branch?

**Comment by rtbs-dev** [comment]
Looks good to me, and the tests pass. @sarahlukens Let me know if I can merge

**Comment by rtbs-dev** [comment]
> how do I create a pull request for the most recent update to this branch?

Any new commits to the branch `sarahlukens-newitem-tlpdatasets` will automatically show up. The PR is just a name for the link between source branch (`sarahlukens-newitem-tlpdatasets`) and target branch (`master`). That link will track all changes to source and compare against target, continuously until merged.

**Comment by sarahlukens** [comment]
Thurston, it's good to merge.  I added the NYC park that I accidently deleted back

**Pull request merged**
